### ISSUE TITLE
Config: standard invoice date, line unit, file name are not applied to new invoices

### ISSUE THREAD

**Issue by jsefiani** [be-pongit/confac-front#102]

**Comment by jsefiani** [comment]
+ group invoices per month not working when set to true in config

**Comment by Laoujin** [comment]
Ik heb van je comment een nieuwe bug gemaakt

**Comment by Laoujin** [comment]
Ik denk dat dit allemaal wel werkt

er is een hierarchie:
- je zet een default op config niveau
- de default op client neemt als default die van de config
- de default op invoice neemt de default van de client (en niet meer van de config)

**Comment by jsefiani** [comment]
Aah oke dan is het in orde.
