### ISSUE TITLE
Attachments are deleted when creating an invoice for a project_month and then deleting that invoice

### ISSUE THREAD

**Issue by jsefiani** [be-pongit/confac-front#113]
Steps to reproduce issue:
- Upload inbound invoice
- Create invoice
- Delete invoice (the attachments are also deleted)

AS IS: 
- When creating an invoice for a project_month, the attachments of the project_month are moved from project_month level to invoice level. When we delete that invoice, all attachments related to it are deleted.

TO BE: 
- When creating an invoice for a project_month, the attachments of the project_month are moved from project_month level to invoice level. When we delete that invoice, all attachments related to it must be moved back to project_month level.

**Comment by Laoujin** [comment]
bug monthlyinvoicing: create invoice, delete, recreate --> the attachments_project_month record still exists (with just an _id) and backend crashes with dup key error when recreating the invoice
