### ISSUE TITLE
Email templates: direct html

### ISSUE THREAD

**Issue by Laoujin** [be-pongit/confac-front#58]
Add a toggle to turn the WYSIWYG email configs into a simple text area where we can simply post HTML and save as is

**Comment by jsefiani** [comment]
What page? Can I get more info?

**Comment by Laoujin** [comment]
Dit is de HtmlInput

Het gaat over: /config -> EmailBody, EmailSignature, EmailReminder
En ook over: /client/id -> EmailBody, ...
En ook over de SendInvoiceEmail modal

Maar dat is allemaal hetzelfde component.
