### ISSUE TITLE
[Technical] Make Redux devtools work

### ISSUE THREAD

**Issue by Laoujin** [be-pongit/confac-front#59]
Right now state can't be viewed from chrome extension

**Comment by jsefiani** [comment]
That's weird because I'm able to use the Redux development tools in Chrome?

**Comment by jsefiani** [comment]
![image](https://user-images.githubusercontent.com/40734088/71896517-49006d00-3154-11ea-91ec-1659adcea23b.png)

**Comment by Laoujin** [comment]
Uhoh... Das vreemd.
Ik zal nog es proberen...

**Comment by Laoujin** [comment]
Hehe oeps... Was een ander project waar het niet werkte...
